channels:
  - conda-forge
dependencies:
  - botocore
  - netifaces
  - openssl
  - paramiko
  - pip
  - pip:
    - posttroll==1.12.1
    - trollmoves==0.16.0
  - python=3.13
  - pyyaml
  - pyzmq
  - requests
  - s3fs>=2025.3.0
  - scp
  - setuptools
  - trollsift==0.6.0
  - watchdog
  - yaml
  - zeromq
  - zlib
