channels:
  - conda-forge
dependencies:
  - botocore<1.36
  - netifaces
  - openssl
  - paramiko
  - pip
  - pip:
    - posttroll==1.12.1
    - trollmoves==0.15.2
  - python=3.12
  - pyyaml
  - pyzmq
  - requests
  - s3fs
  - scp
  - setuptools
  - trollsift
  - watchdog
  - yaml
  - zeromq
  - zlib
