channels:
  - conda-forge
dependencies:
  - botocore
  - netifaces
  - openssl
  - paramiko
  - pip
  - pip:
    - posttroll==1.15.0
    - trollmoves==0.18.0
  - python=3.13
  - pyyaml
  - pyzmq
  - requests
  - s3fs>=2026.4.0
  - scp
  - setuptools
  - trollsift==1.0.0
  - watchdog
  - yaml
  - zeromq
  - zlib
